version: '3.7'

services:
  server_api:
    container_name: server_api
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/dist
      - /usr/src/app/node_modules
    ports:
      - "30:30"
    command: npm run start:dev
    depends_on:
      - mongo_database
    networks:
      - netty
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  mongo_database:
    container_name: database
    image: mongo:latest
    networks:
      - netty
    ports:
      - "27017:27017"
networks:
  netty: