version: '3.0'

services:
  api:
    container_name: api
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "30:30"
    command: npm run start:dev
    depends_on:
      - database
    restart: always
  database:
    container_name: database
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"